version: "3.9"

services:
  # MySQL Database Service
  db:
    image: "mysql:latest"
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: changethisrootpassword
      MYSQL_DATABASE: crm-website
      MYSQL_USER: ChristopherTest
      MYSQL_PASSWORD: Test123!
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
  # Laravel Lumen API Service
  lumen:
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy